pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello Techie'
            }
        }
        stage('Hello 1') {
            steps {
                echo 'Hello Techie 1'
            }
        }
    }
}
